dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^epic\\/.*$/"
    - "/^release\\/.*$/"
    - "/^integration-libs\\/.*$/"
defaults: &defaults
  script: "export CYPRESS_CONFIG=cypress.ci.json && export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
jobs:
  - script: "./ci-scripts/validate-lint.sh"
    name: "Validation checks"
  - script:
    name: "E2E tests for B2C, 1st job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 2st job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 3rd job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 4th job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 5th job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 6th job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 7th job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 8th job"
    <<: *defaults
  - script: "./ci-scripts/e2e-cypress.sh --ssr"
    name: "E2E tests for SSR B2C"
addons:
  chrome: stable
  sonarcloud:
    organization: sap
