on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize, reopened]
name: Spartacus CI pipeline
jobs:
  e2eTests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
