on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - feature/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize, reopened]
name: Spartacus CI pipeline
jobs:
  unitTestsCore:
    name: Unit tests Core
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install angular CLI
        run: npm install -g @angular/cli@latest
      - name: Install yarn
        run: npm install -g yarn
      - name: Package installation
        run: yarn install
      - name: Run unit tests for core and storefront
        run: |
          ls -al         
          ci-scripts/unit-tests-core-lib.sh
  unitTestsLibs:
    name: Unit tests libs
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install angular CLI
        run: npm install -g @angular/cli@latest
      - name: Install yarn
        run: npm install -g yarn
      - name: Package installation
        run: yarn install
      - name: Run unit tests for libs
        run: |
          ls -al         
          ci-scripts/unit-tests-core-lib.sh
  linting:
    name: linting
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install angular CLI
        run: npm install -g @angular/cli@latest
      - name: Install yarn
        run: npm install -g yarn
      - name: Package installation
        run: yarn install
      - name: linting
        run: |
          ls -al         
          ci-scripts/validate-lint.sh
  e2eTestsB2B1:
    name: Cypress e2e tests B2B job1
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
        run: |
          ls -al         
          export SPA_ENV='ci,b2b' && ./ci-scripts/e2e-cypress.sh -s b2b