on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize, reopened]
name: Spartacus CI pipeline
jobs:
  e2eTests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Install cypress dependencies
        run: |
          ls -al
          cd projects/storefrontapp-e2e-cypress && yarn install
          ls -al
      - name: Run e2es
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          SPA_ENV: ci,b2c
        run: ls -al
