on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize, reopened]
name: Spartacus CI pipeline
jobs:
  e2eTests:
    name: Cypress e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Install cypress dependencies
        run: yarn install
          working-directory: projects/storefrontapp-e2e-cypress
      - name: Run e2es
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
        run: ./e2e-cypress.sh
          working-directory: ci-scripts
        env: 
          SPA_ENV: ci,b2c