on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  # push: to remove above once test is ove
  #   branches:
  #     - develop
  workflow_dispatch:
    inputs:
      FROM_TAG:
        description: 'previous release tag version'
        required: true
        default: '5.0.0'
      TO_TAG:
        description: 'current release tag version'
        default: 'HEAD'
name: "Publish Release Draft notes"
jobs:
  preReleaseDraft:
    name: Create pre-release draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install
      - name: Generate changelog
        id: changelog
        run: | 
          changelog=$(npx ts-node scripts/changelog.ts --verbose --from asm-4.0.0)

          # Remove when support for multiline is available
          # https://github.com/actions/toolkit/issues/403
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"

          echo "::set-output name=changelog::$(echo $changelog)"
      - name: Create release draft
        uses: ./.github/publish-release-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}